Repository IIION/Workade, pull requests merged in 2022-10, with the labels that each got.

#1 ✨Feat 홈 화면의 Navigation Bar와 인삿말 Label을 구성했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/ProfileTamna.imageset/Contents.json
  Workade/Assets.xcassets/ProfileTamna.imageset/ProfileTamna.svg
  Workade/Assets.xcassets/WorkadeLogoTamna.imageset/Contents.json
  Workade/Assets.xcassets/WorkadeLogoTamna.imageset/WorkadeLogoTamna.svg
  Workade/Extentions/UIImage+.swift
  Workade/SceneDelegate.swift
  Workade/Views&ViewModels/Home/HomeView.swift
Labels: enhancement, In Review

#3 ✨ 디자인 시스템 코드를 추가했습니다
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/Colors/Background.colorset/Contents.json
  Workade/Assets.xcassets/Colors/Contents.json
  Workade/Assets.xcassets/Colors/GroupedBackground.colorset/Contents.json
  Workade/Assets.xcassets/Colors/LabelBackground.colorset/Contents.json
  Workade/Assets.xcassets/Colors/Primary.colorset/Contents.json
  Workade/Assets.xcassets/Colors/Quaternary.colorset/Contents.json
  Workade/Assets.xcassets/Colors/Secondary.colorset/Contents.json
  Workade/Assets.xcassets/Colors/SubGroupedBackground.colorset/Contents.json
  Workade/Assets.xcassets/Colors/Tertiary.colorset/Contents.json
  Workade/DesignSystem.swift
  Workade/Extentions/Color+.swift
  Workade/Extentions/Font+.swift
  Workade/Fonts/Pretendard-Bold.otf
  Workade/Fonts/Pretendard-Medium.otf
  Workade/Fonts/Pretendard-Regular.otf
  Workade/Fonts/Pretendard-SemiBold.otf
  Workade/Info.plist
Labels: documentation, enhancement

#2 ✨Feat MagazineView 의 Custom TabBar 를 적용 하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Views&ViewModels/Magazine/ColumnDetail/ColumnDetailViewController.swift
  Workade/Views&ViewModels/Magazine/MagazineViewController.swift
  Workade/Views&ViewModels/Magazine/ReviewDetail/ReviewDetailViewController.swift
  Workade/Views&ViewModels/Magazine/TipDetail/TipDetailViewController.swift
  Workade/Views&ViewModels/Magazine/TotalDetail/TotalDetailViewController.swift
Labels: enhancement, In Review

#4 ✨ 체크리스트뷰 기본적인 UI와 레이아웃을 구축하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Models/CheckListModel.swift
  Workade/Views&ViewModels/CheckList/CheckListCell/CheckListCell.swift
  Workade/Views&ViewModels/CheckList/CheckListViewController.swift
Labels: enhancement, In Review

#5 ✨ 오피스 컬렉션뷰와 오피스 컬렉션뷰셀을 구성했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/OpieceTamna.imageset/Contents.json
  Workade/Assets.xcassets/OpieceTamna.imageset/OpieceTamna.svg
  Workade/Extentions/Color+.swift
  Workade/Extentions/Font+.swift
  Workade/Extentions/UICollectionReuableView+.swift
  Workade/Extentions/UICollectionView+.swift
  Workade/Models/HomeModel.swift
  Workade/Views&ViewModels/Home/HomeView.swift
  Workade/Views&ViewModels/Home/HorizontalCollectionView.swift
  Workade/Views&ViewModels/Home/OfficeCollectionViewCell.swift
Labels: enhancement, In Review

#6 ✨ 주변 장소 뷰에서 필요한 세그먼트 컨트롤을 구현했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Views&ViewModels/NearbyPlace/IntroduceView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
  Workade/Views&ViewModels/NearbyPlace/TempGalleryView.swift
Labels: enhancement, In Review

#10 ✨ 체크리스트 디테일 뷰를 구현하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UITableView+.swift
  Workade/Extentions/UITableViewCell+.swift
  Workade/Models/CheckListModel.swift
  Workade/Views&ViewModels/CheckList/CheckListCell/CheckListCell.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailCell/CheckListDetailCell.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListViewController.swift
Labels: enhancement, In Review

#9 ✨TipDetailView의 UI를 구현하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/sampleTipImage.imageset/Contents.json
  Workade/Assets.xcassets/sampleTipImage.imageset/sampleTipImage.jpeg
  Workade/Views&ViewModels/Magazine/MagazineViewController.swift
  Workade/Views&ViewModels/Magazine/TipDetail/TipDetailCell/TipDetailCell.swift
  Workade/Views&ViewModels/Magazine/TipDetail/TipDetailViewController.swift
Labels: 화면구성/View Add, 리뷰 중/In Review

#17 🔥 :bento: swift 파일 명 수정 및 Font 일부 수정했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UIColor+.swift
  Workade/Extentions/UIFont+.swift
Labels: 수정/Modify

#19 :fire: :building_construction: 최소버전 변경 14.0 -> 15.0 으로 변경하였습니다.
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Pods.xcodeproj/xcuserdata/inhochoi.xcuserdatad/xcschemes/xcschememanagement.plist
  Workade.xcodeproj/project.pbxproj
  Workade.xcodeproj/xcuserdata/inhochoi.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: 수정/Modify

#13 ✨ 홈 화면 UI 완성했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/OpieceTamna.imageset/OpieceTamna.svg
  Workade/Assets.xcassets/WorkationTamna.imageset/Contents.json
  Workade/Assets.xcassets/WorkationTamna.imageset/WorkationTamna.svg
  Workade/Extentions/UICollectionReuableView+.swift
  Workade/Extentions/UICollectionView+.swift
  Workade/Extentions/UIImage+.swift
  Workade/Models/HomeModel.swift
  Workade/Views&ViewModels/Home/CollectionView/HorizontalCollectionView.swift
  Workade/Views&ViewModels/Home/CollectionView/MagazineCollectionViewCell.swift
  Workade/Views&ViewModels/Home/CollectionView/OfficeCollectionViewCell.swift
  Workade/Views&ViewModels/Home/HomeView.swift
  Workade/Views&ViewModels/Home/HomeViewController.swift
  Workade/Views&ViewModels/Home/HorizontalCollectionView.swift
  Workade/Views&ViewModels/Home/View/CellImageView.swift
  Workade/Views&ViewModels/Home/View/CheckListButton.swift
  Workade/Views&ViewModels/Home/View/HeaderView.swift
Labels: 화면구성/View Add, 리뷰 완료/End Review, 머지 대기/Ready Merge

#15 ✨ 주변장소 / 갤러리 뷰를 완성했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/AppDelegate.swift
  Workade/Assets.xcassets/GalleryTestImage1.imageset/Contents.json
  Workade/Assets.xcassets/GalleryTestImage1.imageset/skystair.jpeg
  Workade/Assets.xcassets/GalleryTestImage2.imageset/601dd5c3fa4b5ed150659ef09fbf5f6f6ab78900cac8bebccacf06db87034547343bfcbdec1d432406cdb49211e290dbc57b77ace54f4c029a24445c47f3145fb55257185ede21de81a1a9623e50e8abe61e806b5b890f92250809e4f915574b22d5780ced2072f3996642f57a50dbe2.jpeg
  Workade/Assets.xcassets/GalleryTestImage2.imageset/Contents.json
  Workade/Assets.xcassets/GalleryTestImage3.imageset/Contents.json
  Workade/Assets.xcassets/GalleryTestImage3.imageset/sunghoon-kim-efAYaRFwm18-unsplash.jpg
  Workade/Assets.xcassets/GalleryTestImage4.imageset/Contents.json
  Workade/Assets.xcassets/GalleryTestImage4.imageset/ori-song-H819CP2ad-g-unsplash.jpg
  Workade/Extentions/UIColor+.swift
  Workade/Extentions/UIFont+.swift
  Workade/Views&ViewModels/Gallery/CardTransitionManager.swift
  Workade/Views&ViewModels/Gallery/GalleryCollectionViewCell.swift
  Workade/Views&ViewModels/Gallery/GalleryDetailViewController.swift
  Workade/Views&ViewModels/Gallery/GalleryViewController.swift
  Workade/Views&ViewModels/Gallery/GalleryViewModel.swift
  Workade/Views&ViewModels/Gallery/UICollectionViewTwoLineLayout.swift
Labels: 화면구성/View Add, 리뷰 중/In Review

#18 ✨ TipItemDetailView 에 Scroll View를 적용하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UIButton+.swift
  Workade/Share/CustomNavigationBar.swift
  Workade/Views&ViewModels/Magazine/TipDetail/MagazineDetailView.swift
  Workade/Views&ViewModels/Magazine/TipDetail/TipDetailViewController.swift
  Workade/Views&ViewModels/Magazine/TipDetail/TipItemDetailViewController.swift
Labels: 기능 추가/Enhancement, 리뷰 중/In Review

#20 🔥🍱 UIColor Extension의 ColorTheme에서 잘못된 SwiftUI 코드 활용을 수정하였습니다.
  Workade/Extentions/UIColor+.swift
Labels: 수정/Modify

#16 ✨ 네이버 맵 및 상단 정보를 표시하였습니다.
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Pods.xcodeproj/xcuserdata/inhochoi.xcuserdatad/xcschemes/Pods-Workade.xcscheme
  Pods/Pods.xcodeproj/xcuserdata/inhochoi.xcuserdatad/xcschemes/xcschememanagement.plist
  Pods/Target Support Files/Pods-Workade/Pods-Workade-acknowledgements.markdown
  Pods/Target Support Files/Pods-Workade/Pods-Workade-acknowledgements.plist
  Pods/Target Support Files/Pods-Workade/Pods-Workade.debug.xcconfig
  Pods/Target Support Files/Pods-Workade/Pods-Workade.release.xcconfig
  Workade.xcodeproj/project.pbxproj
  Workade/Share/BasePaddingLabel.swift
  Workade/Views&ViewModels/Map/MapViewController.swift
Labels: 화면구성/View Add, 리뷰 완료/End Review

#25 ✨ 마이페이지, 설정 뷰컨 구성했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UICollectionView+.swift
  Workade/Extentions/UIImage+.swift
  Workade/Extentions/UINavigationController.swift
  Workade/Share/TitleView.swift
  Workade/Views&ViewModels/Home/HomeViewController.swift
  Workade/Views&ViewModels/Home/View/CheckListButton.swift
  Workade/Views&ViewModels/MyPage/MyPageViewController.swift
  Workade/Views&ViewModels/SettingViewController/SettingViewController.swift
Labels: 화면구성/View Add, 머지 대기/Ready Merge

#24 ✨ 체크리스트 디테일 페이지의 투두리스트 CRUD 기능을 추가하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListBottomSheet/CheckListBottomSheetViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailCell/CheckListDetailCell.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewModel.swift
  Workade/Views&ViewModels/CheckList/CheckListViewController.swift
Labels: 버그/Bug, 기능 추가/Enhancement, 리뷰 중/In Review

#27 ✨ 주변 장소 뷰에서 데이터 로드, 스크롤 뷰, 네비게이션 바 구현 완료 했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UIFont+.swift
  Workade/Models/DetailDataModel.swift
  Workade/Views&ViewModels/NearbyPlace/IntroduceView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
  Workade/Views&ViewModels/NearbyPlace/TempNavigationBar.swift
Labels: 화면구성/View Add, 기능 추가/Enhancement, 머지 대기/Ready Merge

#28 ♻️ 공통으로 사용될 Close Button 디자인과 MagazineViewController의 레이아웃을 수정하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UIButton+.swift
  Workade/Share/CustomNavigationBar.swift
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
  Workade/Views&ViewModels/Magazine/ColumnDetail/ColumnDetailViewController.swift
  Workade/Views&ViewModels/Magazine/MagazineDetailView.swift
  Workade/Views&ViewModels/Magazine/MagazineViewController.swift
  Workade/Views&ViewModels/Magazine/ReviewDetail/ReviewDetailViewController.swift
  Workade/Views&ViewModels/Magazine/TapDetailCell/TapDetailCell.swift
  Workade/Views&ViewModels/Magazine/TapDetailViewController.swift
  Workade/Views&ViewModels/Magazine/TotalDetail/TotalDetailViewController.swift
Labels: 리뷰 중/In Review, 수정/Modify

#35 ♻️ NearbyPlaceController에 GalleryView를 연결하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Views&ViewModels/Gallery/GalleryViewController.swift
  Workade/Views&ViewModels/Gallery/GalleryViewModel.swift
  Workade/Views&ViewModels/NearbyPlace/Gallery/CardTransitionManager.swift
  Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryCollectionViewCell.swift
  Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryDetailViewController.swift
  Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
  Workade/Views&ViewModels/NearbyPlace/Gallery/UICollectionViewTwoLineLayout.swift
  Workade/Views&ViewModels/NearbyPlace/GalleryView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
  Workade/Views&ViewModels/NearbyPlace/TempGalleryView.swift
Labels: 리뷰 중/In Review, 수정/Modify

#36 🔥 프로젝트 파일 수정
  Workade.xcodeproj/project.pbxproj
  Workade/Views&ViewModels/Home/HomeViewController.swift
  Workade/Views&ViewModels/MyPage/MyPageViewController.swift
Labels: 버그/Bug

#31 ✨ Checklist Template Cell 및 Detail Controller를 구현하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/folder.imageset/Contents.json
  Workade/Assets.xcassets/folder.imageset/FOLDER.png
  Workade/SceneDelegate.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateCell.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateModel.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateViewModel.swift
Labels: 화면구성/View Add, 리뷰 완료/End Review

#30 ✨ Event 유무에 따라 EventView가 표시 되도록 구현했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Views&ViewModels/Home/HomeViewController.swift
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
  Workade/Views&ViewModels/Magazine/MagazineDetailView.swift
  Workade/Views&ViewModels/Magazine/MagazineViewController.swift
  Workade/Views&ViewModels/Magazine/TapDetailViewController.swift
Labels: 기능 추가/Enhancement, 리뷰 중/In Review

#34 ✨ 체크리스트의 날짜, 이모지 변경 기능을 추가하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Views&ViewModels/CheckList/CheckListCell/CheckListAddButtonCell.swift
  Workade/Views&ViewModels/CheckList/CheckListCell/CheckListCell.swift
  Workade/Views&ViewModels/CheckList/CheckListCell/CheckListCellViewModel.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailCell/CheckListDetailCell.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewModel.swift
  Workade/Views&ViewModels/CheckList/CheckListViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListViewModel.swift
  Workade/Views&ViewModels/CheckList/EmojiPicker/EmojiPickerController.swift
Labels: 기능 추가/Enhancement, 리뷰 중/In Review

#32 :sparkles: Map에 특정 지도 지정 및 마커를 표시했습니다.
  Pods/Pods.xcodeproj/xcuserdata/inhochoi.xcuserdatad/xcschemes/xcschememanagement.plist
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/Map/Contents.json
  Workade/Assets.xcassets/Map/cafepin.imageset/Contents.json
  Workade/Assets.xcassets/Map/cafepin.imageset/cafepin.pdf
  Workade/Assets.xcassets/Map/naturepin.imageset/Contents.json
  Workade/Assets.xcassets/Map/naturepin.imageset/naturepin.pdf
  Workade/Assets.xcassets/Map/restaurantpin.imageset/Contents.json
  Workade/Assets.xcassets/Map/restaurantpin.imageset/restaurantpin.pdf
  Workade/Assets.xcassets/Map/seapin.imageset/Contents.json
  Workade/Assets.xcassets/Map/seapin.imageset/seapin.pdf
  Workade/Assets.xcassets/Map/selectedcafepin.imageset/Contents.json
  Workade/Assets.xcassets/Map/selectedcafepin.imageset/selectedcafepin.pdf
  Workade/Assets.xcassets/Map/selectednaturepin.imageset/Contents.json
  Workade/Assets.xcassets/Map/selectednaturepin.imageset/selectednaturepin.pdf
  Workade/Assets.xcassets/Map/selectedrestaurantpin.imageset/Contents.json
  Workade/Assets.xcassets/Map/selectedrestaurantpin.imageset/selectedrestaurantpin.pdf
  Workade/Assets.xcassets/Map/selectedseapin.imageset/Contents.json
  Workade/Assets.xcassets/Map/selectedseapin.imageset/selectedseapin.pdf
  Workade/Models/MapPinModel.swift
  Workade/Views&ViewModels/Map/MapViewController.swift
Labels: 화면구성/View Add, 기능 추가/Enhancement, 리뷰 중/In Review

#39 ✨ 주변 장소 뷰 데이터 연결을 완료했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UILabel+.swift
  Workade/Models/HomeModel.swift
  Workade/Share/CustomNavigationBar.swift
  Workade/Views&ViewModels/NearbyPlace/Gallery/UICollectionViewTwoLineLayout.swift
  Workade/Views&ViewModels/NearbyPlace/IntroduceView.swift
  Workade/Views&ViewModels/NearbyPlace/IntroduceViewModel.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
Labels: 기능 추가/Enhancement

#38 ✨🍱 런치 스크린을 추가했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/AppIcon.appiconset/1024.png
  Workade/Assets.xcassets/AppIcon.appiconset/Contents.json
  Workade/Assets.xcassets/iconTransperent.imageset/Contents.json
  Workade/Assets.xcassets/iconTransperent.imageset/logoTransperent.png
  Workade/Assets.xcassets/launch.imageset/Contents.json
  Workade/Assets.xcassets/launch.imageset/launch.png
  Workade/Base.lproj/LaunchScreen.storyboard
  Workade/LaunchScreenAnimationView.swift
  Workade/Views&ViewModels/Home/HomeViewController.swift
Labels: 문서/Document, 화면구성/View Add, 기능 추가/Enhancement

#41 ✨ Bookmark 관련 로직을 구성했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Managers/BookmarkManager.swift
  Workade/Managers/ImageCacheManager.swift
  Workade/Managers/NetworkManager.swift
  Workade/Managers/UserDefaultsManager.swift
  Workade/Views&ViewModels/Home/Binder.swift
  Workade/Views&ViewModels/Home/CollectionView/CollectionViewCellDelegate.swift
  Workade/Views&ViewModels/Home/CollectionView/MagazineCollectionViewCell.swift
  Workade/Views&ViewModels/Home/CollectionView/OfficeCollectionViewCell.swift
  Workade/Views&ViewModels/Home/Constants.swift
  Workade/Views&ViewModels/Home/HomeViewController.swift
  Workade/Views&ViewModels/Home/HomeViewModel.swift
  Workade/Views&ViewModels/Home/MultiBinder.swift
  Workade/Views&ViewModels/MyPage/MyPageViewController.swift
  Workade/Views&ViewModels/MyPage/MyPageViewModel.swift
Labels: 화면구성/View Add, 기능 추가/Enhancement, help wanted

#40 :sparkles: MapViewController ViewModel 분리 및 Home과 연결했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/AppDelegate.swift
  Workade/Models/HomeModel.swift
  Workade/Views&ViewModels/Home/HomeViewController.swift
  Workade/Views&ViewModels/Map/MapViewController.swift
  Workade/Views&ViewModels/Map/MapViewModel.swift
Labels: 기능 추가/Enhancement

#43 ✨ 주변 장소 뷰에서 지도로 오피스 정보 넘기기 로직 작성
  Workade/Share/CustomNavigationBar.swift
  Workade/Views&ViewModels/Map/MapViewController.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
Labels: 기능 추가/Enhancement, 추후 코드리뷰/CodeReview Later

#42 ✨ 체크리스트 템플릿을 불러오는 기능을 추가하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListBottomSheet/CheckListBottomSheetViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListBottomSheet/CheckListBottomSheetViewModel.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/TitlePopOverViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateCell.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateModel.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateViewModel.swift
Labels: 기능 추가/Enhancement

#47 🔥 navigationBar 삭제
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
Labels: 버그/Bug, 추후 코드리뷰/CodeReview Later
