Repository IIION/Workade, pull requests merged in 2022-12, with the labels that each got.

#109 :sparkles: 인원수 표기 뷰-네트워크 로직을 연결했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/ExploreBackground/jeJuDoBackground.imageset/Contents.json
  Workade/Assets.xcassets/ExploreBackground/jeJuDoBackground.imageset/jeJuDoBackground.png
  Workade/Managers/ExploreTransitionManager.swift
  Workade/Models/MapViewModel.swift
  Workade/Models/RegionModel.swift
  Workade/Models/UserModel.swift
  Workade/Share/RegionButton.swift
  Workade/Views&ViewModels/Explore/ExploreViewController.swift
  Workade/Views&ViewModels/Explore/ExploreViewModel.swift
  Workade/Views&ViewModels/Explore/RegionInfoView.swift
Labels: 기능 추가/Enhancement, 수정/Modify

#110 ♻️ Mypage관련 Viewmodel 을 연결하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Managers/FirebaseManager.swift
  Workade/Managers/FirestoreManager.swift
  Workade/Views&ViewModels/MyPage/EditProfile/EditProfileViewController.swift
  Workade/Views&ViewModels/MyPage/MyPageViewController.swift
  Workade/Views&ViewModels/MyPage/MyPageViewModel/MyPageViewModel.swift
  Workade/Views&ViewModels/MyPage/MyPageViewModel/SettingViewModel.swift
  Workade/Views&ViewModels/MyPage/ProfileView.swift
  Workade/Views&ViewModels/MyPage/Setting/LoginInformationView.swift
  Workade/Views&ViewModels/MyPage/Setting/SettingViewController.swift
Labels: 기능 추가/Enhancement

#114 ♻️ 중복된 로그아웃 함수 제거
  Workade/Managers/FirebaseManager.swift
  Workade/Views&ViewModels/MyPage/MyPageViewModel/SettingViewModel.swift
  Workade/Views&ViewModels/MyPage/Setting/LoginInformationView.swift
  Workade/Views&ViewModels/MyPage/Setting/SettingViewController.swift
Labels: 리팩토링/Refactoring

#115 :bug: ExploreViewController <-> WorkationViewController 간의 트렌지션 매니저 미적용 수정하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Managers/ExploreTransitionManager.swift
  Workade/Views&ViewModels/Explore/ExploreViewController.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
Labels: 기능 추가/Enhancement, 리뷰 완료/End Review

#117 :bug: 워케이션에 따라 WorkationViewController 네브바 버튼 변경되도록 수정 및 워케이션 시작 종료 시 Alert가 나타나도록 변경했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Managers/ExploreTransitionManager.swift
  Workade/Views&ViewModels/Explore/ExploreViewController.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
Labels: 수정/Modify

#116 :sparkles: 각 뷰의 Login 연결
  Workade.xcodeproj/project.pbxproj
  Workade/Managers/FirebaseManager.swift
  Workade/Managers/FirestoreManager.swift
  Workade/Managers/UserManager.swift
  Workade/Models/UserModel.swift
  Workade/Views&ViewModels/Explore/ExploreViewController.swift
  Workade/Views&ViewModels/Login/LoginInitViewController.swift
  Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
  Workade/Views&ViewModels/Login/LoginName/LoginNameViewController.swift
  Workade/Views&ViewModels/Login/LoginSheetView.swift
  Workade/Views&ViewModels/MyPage/EditProfile/EditProfileViewController.swift
  Workade/Views&ViewModels/MyPage/MyPageViewController.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
  Workade/Views&ViewModels/Workation/WorkerStatusSheet/WorkerStatusSheetViewController.swift
  Workade/Views&ViewModels/Workation/WorkerStatusSheet/WorkerStatusSheetViewModel.swift
Labels: 기능 추가/Enhancement

#118 :sparkles: ActiveRegion 정보 저장
  Workade/Managers/FirebaseManager.swift
  Workade/Managers/FirestoreManager.swift
  Workade/Managers/UserManager.swift
  Workade/Views&ViewModels/MyPage/Setting/SettingViewController.swift
Labels: 기능 추가/Enhancement

#119 ✨ 현재 위치 정보 데이터 바인딩
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
  Workade/Views&ViewModels/Workation/WorkationViewModel.swift
Labels: 기능 추가/Enhancement

#121 ✨ 흰색 글씨 및 북마크 버튼 가독성을 위해 옅은 검정 색상 레이어 및 뷰 추가했습니다.
  Workade/Utils/Constants.swift
  Workade/Views&ViewModels/GuideHome/View/CellImageView.swift
  Workade/Views&ViewModels/Magazine/TitleImageView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceImageView.swift
Labels: 화면구성/View Add

#126 ✨ 워케이션 시작시 프로그래스 바, 워케이션 시작 날짜 변경했습니다
  Workade.xcodeproj/project.pbxproj
  Workade.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Workade.xcodeproj/xcshareddata/xcschemes/Workade.xcscheme
  Workade/Managers/FirestoreManager.swift
  Workade/Managers/UserManager.swift
  Workade/Views&ViewModels/Workation/StickerProgress/StickerProgressView.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
Labels: 기능 추가/Enhancement

#127 :bug: 회원탈퇴 버그 수정
  Workade/Managers/FirebaseManager.swift
  Workade/Managers/FirestoreManager.swift
  Workade/Models/UserModel.swift
  Workade/SceneDelegate.swift
  Workade/Views&ViewModels/Explore/ExploreViewController.swift
  Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
  Workade/Views&ViewModels/Login/LoginSheetView.swift
  Workade/Views&ViewModels/MyPage/EditProfile/EditProfileViewController.swift
  Workade/Views&ViewModels/MyPage/MyPageViewController.swift
  Workade/Views&ViewModels/MyPage/Setting/SettingViewController.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
Labels: 버그/Bug, 기능 추가/Enhancement

#128 ✨ 스티커를 위한 경과일 데이터 모델 추가
  Workade/Managers/FirestoreManager.swift
  Workade/Models/UserModel.swift
  Workade/Views&ViewModels/Workation/StickerProgress/StickerProgressView.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
Labels: 기능 추가/Enhancement

#129 :sparkles: 스티커 로직을 위한 코드 수정 및 추가했습니다.
  Workade/Models/StickerModel.swift
  Workade/Views&ViewModels/Workation/StickerProgress/StickerProgressView.swift
  Workade/Views&ViewModels/Workation/StickerSheet/StickerSheetViewController.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
Labels: 기능 추가/Enhancement

#130 ✨ 네트워크 상태를 체크하는 NetworkMonitor 객체를 정의 및 연결했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Managers/NetworkMonitor.swift
  Workade/Views&ViewModels/GuideHome/GuideHomeViewModel.swift
  Workade/Views&ViewModels/Login/LoginView.swift
Labels: 기능 추가/Enhancement

#132 :bug: 앱 재접속 이후 워케이션 뷰 안보이는 버그 수정하였습니다.
  Workade/Managers/FirebaseManager.swift
  Workade/Managers/FirestoreManager.swift
  Workade/Models/UserModel.swift
  Workade/SceneDelegate.swift
  Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
  Workade/Views&ViewModels/MyPage/Setting/SettingViewController.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
Labels: 버그/Bug

#134 :sparkles: 로그인 버튼의 디자인을 변경했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/Login/applelogo.imageset/Contents.json
  Workade/Assets.xcassets/Login/applelogo.imageset/applelogo.pdf
  Workade/Assets.xcassets/Login/applelogo.imageset/􀣺.svg
  Workade/Views&ViewModels/Login/Element/LoginButtonView.swift
  Workade/Views&ViewModels/Login/LoginSheetView.swift
Labels: 기능 추가/Enhancement, 수정/Modify

#135 ✨ 웹뷰 호출로 License와 개인정보 처리 방침을 적용 하였습니다.
  Workade/Views&ViewModels/MyPage/Setting/SettingViewController.swift
Labels: 화면구성/View Add

#139 ♻️ 직업 라벨 색깔을 현재 직업에 따라 보이도록 변경했습니다.
  Workade/Views&ViewModels/Workation/WorkerStatusSheet/WorkerStatusSheetViewController.swift
Labels: 리팩토링/Refactoring

#141 :bug: 지역별 워케이션 활동 수가 동일하지 않는 버그를 수정하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Managers/FirebaseManager.swift
  Workade/Managers/FirestoreManager.swift
  Workade/Managers/UserManager.swift
  Workade/SceneDelegate.swift
  Workade/Share/RegionButton.swift
  Workade/Views&ViewModels/Explore/ExploreViewController.swift
  Workade/Views&ViewModels/Explore/RegionInfoView.swift
  Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
  Workade/Views&ViewModels/MyPage/EditProfile/EditProfileViewController.swift
  Workade/Views&ViewModels/MyPage/MyPageViewController.swift
  Workade/Views&ViewModels/MyPage/ProfileView.swift
  Workade/Views&ViewModels/MyPage/Setting/SettingViewController.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
  Workade/Views&ViewModels/Workation/WorkerStatusSheet/WorkerStatusSheetViewController.swift
  Workade/Views&ViewModels/Workation/WorkerStatusSheet/WorkerStatusSheetViewModel.swift
Labels: 버그/Bug

#142 🏗️ 버전 업 및 린트 Warning을 제거하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/AppIcon.appiconset/Contents.json
  Workade/Assets.xcassets/AppIcon.appiconset/appicon.jpg
  Workade/Assets.xcassets/AppIcon.appiconset/logo.png
  Workade/Assets.xcassets/Jejudo Map/Namwon2.imageset/Contents.json
  Workade/Assets.xcassets/Jejudo Map/Namwon2.imageset/Namwon.svg
  Workade/Managers/FirebaseManager.swift
  Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
  Workade/Views&ViewModels/MyPage/EditProfile/EditProfileViewController.swift
  Workade/Views&ViewModels/Workation/WorkerStatusSheet/WorkerStatusSheetViewController.swift
Labels: 버전 업

#143 ♻️ 필요없는 폰트 가이드라인을 제거했습니다
  Workade/Extentions/UIFont+.swift
  Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
  Workade/Views&ViewModels/Login/LoginName/LoginNameViewController.swift
  Workade/Views&ViewModels/Login/LoginView.swift
  Workade/Views&ViewModels/MyPage/Setting/LoginInformationView.swift
  Workade/Views&ViewModels/MyPage/Setting/SettingViewController.swift
  Workade/Views&ViewModels/NearbyPlace/Map/MapInfoView.swift
  Workade/Views&ViewModels/Workation/StickerSheet/StickerSheetViewController.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
  Workade/Views&ViewModels/Workation/WorkerStatusSheet/WorkerStatusSheetViewController.swift
Labels: 리팩토링/Refactoring

#147 ♻️ 워케이션 시작시 직업 라벨 컬러 변경 로직 수정
  Workade/Views&ViewModels/Workation/WorkerStatusSheet/WorkerStatusSheetViewController.swift
Labels: 리팩토링/Refactoring

#148 🔥 세팅 뷰에서 빌드 버전 표기를 수정하였습니다.
  Workade/Views&ViewModels/MyPage/Setting/SettingViewController.swift
Labels: 리팩토링/Refactoring
