Repository IIION/Workade, pull requests merged in 2022-11, with the labels that each got.

#48 🍱 가로모드를 막고 Lint 한 줄 최대 글자수를 늘렸습니다.
  .swiftlint.yml
  Pods/Pods.xcodeproj/project.pbxproj
  Workade.xcodeproj/project.pbxproj
Labels: 머지 대기/Ready Merge, 수정/Modify

#52 ♻️ 내비게이션 뷰의 Back Button을 수정하고 Close 버튼을 활성화 했습니다.
  Workade/Share/CustomNavigationBar.swift
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
  Workade/Views&ViewModels/Magazine/MagazineDetailView.swift
  Workade/Views&ViewModels/Magazine/MagazineViewController.swift
Labels: 버그/Bug

#51 ♻️ 내비게이션 바를 재 활성화 하고 이미지 깨지는 버그를 수정했습니다.
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
Labels: 버그/Bug

#53 ♻️ ViewModel 과 Model 수정 및 북마크 버튼 활성화
  Workade/Models/MagazineModel.swift
  Workade/Views&ViewModels/Home/Binder.swift
  Workade/Views&ViewModels/Home/HomeViewController.swift
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
  Workade/Views&ViewModels/Magazine/MagazineDetailView.swift
  Workade/Views&ViewModels/Magazine/MagazineViewController.swift
  Workade/Views&ViewModels/Magazine/MagazineViewModel/MagazineDetailViewModel.swift
  Workade/Views&ViewModels/Magazine/TapDetailViewController.swift
Labels: 기능 추가/Enhancement, 수정/Modify, 리팩토링/Refactoring

#57 ♻️ 북마크 관련 오류를 수정하고 MagazineDetailView 에서 북마크 버튼을 활성화 했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UIImage+.swift
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
  Workade/Views&ViewModels/Magazine/MagazineViewModel/MagazineDetailViewModel.swift
  Workade/Views&ViewModels/Magazine/MagazineViewModel/MagazineViewModel.swift
  Workade/Views&ViewModels/Magazine/TapDetailViewController.swift
Labels: 버그/Bug, 기능 추가/Enhancement, 수정/Modify

#54 ♻️ 이미지 fetch관련 몇 가지 수정했습니다.
  Workade/Extentions/UIImageView+.swift
  Workade/Managers/BookmarkManager.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateCell.swift
  Workade/Views&ViewModels/Home/CollectionView/MagazineCollectionViewCell.swift
  Workade/Views&ViewModels/Home/CollectionView/OfficeCollectionViewCell.swift
  Workade/Views&ViewModels/Home/HomeViewController.swift
  Workade/Views&ViewModels/Home/MultiBinder.swift
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
  Workade/Views&ViewModels/MyPage/MyPageViewController.swift
  Workade/Views&ViewModels/MyPage/MyPageViewModel.swift
  Workade/Views&ViewModels/NearbyPlace/IntroduceViewModel.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
Labels: 리팩토링/Refactoring

#55 ✨ GalleryView에 Pagination 기능을 추가했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Views&ViewModels/NearbyPlace/Gallery/CardTransitionManager.swift
  Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryDetailViewController.swift
  Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryView.swift
  Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryViewModel.swift
  Workade/Views&ViewModels/NearbyPlace/Gallery/UICollectionViewTwoLineLayout.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
Labels: 기능 추가/Enhancement, 리뷰 완료/End Review, 수정/Modify, 리팩토링/Refactoring

#61 🔥 불필요한 코드 제거
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
Labels: 버그/Bug

#50 ♻️ 스프린트 1에서 기획된 체크리스트 템플릿 추가 기능을 완료하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UIColor+.swift
  Workade/Managers/NetworkManager.swift
  Workade/Models/CheckListTemplateModel.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListBottomSheet/CheckListBottomSheetViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListBottomSheet/CheckListBottomSheetViewModel.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewModel.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateCell.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateViewModel.swift
  Workade/Views&ViewModels/CheckList/CheckListViewController.swift
Labels: 기능 추가/Enhancement, 리뷰 완료/End Review, 리팩토링/Refactoring

#62 🔥 함수의 전달인자를 수정하고, 필요하지 않은 Task 변수를 삭제했습니다.
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateViewController.swift
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
Labels: 버그/Bug

#58 ✨ CustomNavigationBar 의 Bookmark 로직을 추가 하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UIImage+.swift
  Workade/Share/CustomNavigationBar.swift
  Workade/Share/GradientView.swift
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
  Workade/Views&ViewModels/Magazine/MagazineViewModel/MagazineDetailViewModel.swift
  Workade/Views&ViewModels/Magazine/MagazineViewModel/MagazineViewModel.swift
  Workade/Views&ViewModels/MyPage/MyPageViewController.swift
  Workade/Views&ViewModels/NearbyPlace/TempNavigationBar.swift
Labels: 기능 추가/Enhancement, 수정/Modify

#63 🐛 로고 이미지 짤림 수정
  Workade/Assets.xcassets/iconTransperent.imageset/Contents.json
  Workade/Assets.xcassets/iconTransperent.imageset/logo.pdf
  Workade/Assets.xcassets/iconTransperent.imageset/logoTransperent.png
Labels: 수정/Modify

#64 ♻️ EmojiPickerController 리팩토링을 진행했습니다.
  Workade/Views&ViewModels/CheckList/EmojiPicker/EmojiPickerController.swift
Labels: 리팩토링/Refactoring

#56 ✨ 주변 장소 뷰에서 네비게이션 바 지도와 연결하였습니다.
  Pods/Pods.xcodeproj/project.pbxproj
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/CGFloat+.swift
  Workade/Extentions/UIImage+.swift
  Workade/Share/CustomNavigationBar.swift
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
  Workade/Views&ViewModels/NearbyPlace/Gallery/GalleryView.swift
  Workade/Views&ViewModels/NearbyPlace/IntroduceView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
Labels: 기능 추가/Enhancement

#65 :building_construction: 프로젝트 기본 값 재설정
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Pods.xcodeproj/xcuserdata/inhochoi.xcuserdatad/xcschemes/Pods-Workade.xcscheme
  Pods/Pods.xcodeproj/xcuserdata/inhochoi.xcuserdatad/xcschemes/xcschememanagement.plist
  Workade.xcodeproj/project.pbxproj
Labels: 수정/Modify

#71 ♻️ 기존의 nearbyPlaceView를 ViewController로 구분 하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UIImage+.swift
  Workade/Extentions/UINavigationController.swift
  Workade/Managers/CardTransitionManager.swift
  Workade/Models/GalleryModel.swift
  Workade/Share/CustomNavigationBar.swift
  Workade/Views&ViewModels/Home/HomeViewController.swift
  Workade/Views&ViewModels/Magazine/MagazineDetailView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceDetailView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceImageView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewModel/GalleryViewModel.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewModel/IntroduceViewModel.swift
Labels: 기능 추가/Enhancement, 수정/Modify, 리팩토링/Refactoring

#72 ♻️ 폴더트리를 변경 및 몇몇 CodingKeys를 제거했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UINavigationController+.swift
  Workade/Managers/NetworkManager.swift
  Workade/Models/CheckListTemplateResource.swift
  Workade/Models/GalleryResource.swift
  Workade/Models/MagazineDetailResource.swift
  Workade/Models/MagazineResource.swift
  Workade/Models/OfficeDetailResource.swift
  Workade/Models/OfficeResource.swift
  Workade/Share/CustomNavigationBar.swift
  Workade/Share/CustomSegmentedControl.swift
  Workade/Utils/Binder.swift
  Workade/Utils/Constants.swift
  Workade/Utils/MultiBinder.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListViewController.swift
  Workade/Views&ViewModels/Home/HomeViewController.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewModel/GalleryViewModel.swift
Labels: 리팩토링/Refactoring

#74 :sparkles: MapInfoView를 추가하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/Map/cafeinfo.imageset/Contents.json
  Workade/Assets.xcassets/Map/cafeinfo.imageset/cafeinfo.pdf
  Workade/Assets.xcassets/Map/natureinfo.imageset/Contents.json
  Workade/Assets.xcassets/Map/natureinfo.imageset/natureinfo.pdf
  Workade/Assets.xcassets/Map/navermapbutton.imageset/Contents.json
  Workade/Assets.xcassets/Map/navermapbutton.imageset/navermapbutton.pdf
  Workade/Assets.xcassets/Map/restaurantinfo.imageset/Contents.json
  Workade/Assets.xcassets/Map/restaurantinfo.imageset/restaurantinfo.pdf
  Workade/Assets.xcassets/Map/seainfo.imageset/Contents.json
  Workade/Assets.xcassets/Map/seainfo.imageset/sea.pdf
  Workade/Extentions/UIFont+.swift
  Workade/Views&ViewModels/Map/MapInfoView.swift
  Workade/Views&ViewModels/Map/MapViewController.swift
  Workade/Views&ViewModels/Map/MapViewModel.swift
Labels: 화면구성/View Add, 리뷰 중/In Review

#76 🍱 디자인 시스템을 2차 하이파이에 맞게 반영하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/Colors/WorkadeBlue.colorset/Contents.json
  Workade/Assets.xcassets/ContentColors/Blue.colorset/Contents.json
  Workade/Assets.xcassets/ContentColors/Contents.json
  Workade/Assets.xcassets/ContentColors/Green.colorset/Contents.json
  Workade/Assets.xcassets/ContentColors/Pink.colorset/Contents.json
  Workade/Assets.xcassets/ContentColors/Purple.colorset/Contents.json
  Workade/Assets.xcassets/ContentColors/Red.colorset/Contents.json
  Workade/Assets.xcassets/ContentColors/Yellow.colorset/Contents.json
  Workade/DesignSystem.swift
  Workade/Extentions/UIColor+.swift
  Workade/Extentions/UIFont+.swift
  Workade/Info.plist
  Workade/Views&ViewModels/Satoshi-Black.otf
  Workade/Views&ViewModels/Satoshi-Bold.otf
  Workade/Views&ViewModels/Satoshi-Medium.otf
  Workade/Views&ViewModels/Satoshi-Regular.otf
Labels: 문서/Document, 수정/Modify

#78 ♻️ MyPage의 버튼들을 활성화 시켰습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Views&ViewModels/MyPage/EditProfile/EditProfileViewController.swift
  Workade/Views&ViewModels/MyPage/MyPageViewController.swift
  Workade/Views&ViewModels/MyPage/ProfileView.swift
  Workade/Views&ViewModels/MyPage/StickerCollectionViewCell.swift
  Workade/Views&ViewModels/SettingViewController/SettingViewController.swift
Labels: 기능 추가/Enhancement

#79 ✨ GuideHomeVC(구 Home)을 새로 구성했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/WorkationTamna.imageset/WorkationTamna.svg
  Workade/Assets.xcassets/checkListCell.imageset/Contents.json
  Workade/Assets.xcassets/checkListCell.imageset/checkListCell.png
  Workade/Extentions/UICollectionView+.swift
  Workade/Extentions/UIFont+.swift
  Workade/Extentions/UIImage+.swift
  Workade/SceneDelegate.swift
  Workade/Share/Divider.swift
  Workade/Utils/Binder.swift
  Workade/Views&ViewModels/CheckList/CheckListViewController.swift
  Workade/Views&ViewModels/GuideHome/GuideHomeViewController.swift
  Workade/Views&ViewModels/GuideHome/GuideHomeViewModel.swift
  Workade/Views&ViewModels/GuideHome/View/CellImageView.swift
  Workade/Views&ViewModels/GuideHome/View/CheckListNavigationCell.swift
  Workade/Views&ViewModels/GuideHome/View/HeaderView.swift
  Workade/Views&ViewModels/GuideHome/View/MagazineCollectionViewCell.swift
  Workade/Views&ViewModels/GuideHome/View/OfficeCollectionViewCell.swift
  Workade/Views&ViewModels/Home/CollectionView/CollectionViewCellDelegate.swift
  Workade/Views&ViewModels/Home/HomeViewController.swift
  Workade/Views&ViewModels/Home/HomeViewModel.swift
  Workade/Views&ViewModels/Home/View/CheckListButton.swift
  Workade/Views&ViewModels/Home/View/HeaderView.swift
  Workade/Views&ViewModels/Magazine/MagazineViewController.swift
  Workade/Views&ViewModels/MyPage/MyPageViewModel/MyPageViewModel.swift
  Workade/Views&ViewModels/Office/OfficeViewController.swift
  Workade/Views&ViewModels/SettingViewController/SettingViewController.swift
Labels: 화면구성/View Add, 기능 추가/Enhancement, 리팩토링/Refactoring

#80 ✨ 오피스, 매거진 뷰컨트롤러의 세그먼트 컨트롤을 커스텀하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Share/EllipseButton.swift
  Workade/Share/EllipseSegmentControl.swift
  Workade/Share/TitleLabel.swift
  Workade/Views&ViewModels/GuideHome/GuideHomeViewController.swift
  Workade/Views&ViewModels/Magazine/MagazineViewController.swift
  Workade/Views&ViewModels/Office/OfficeViewController.swift
  Workade/Views&ViewModels/SettingViewController/SettingViewController.swift
Labels: 화면구성/View Add, 기능 추가/Enhancement

#83 ✨ OfficeViewController를 구성했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Models/OfficeResource.swift
  Workade/Share/Divider.swift
  Workade/Share/PrepareView.swift
  Workade/Views&ViewModels/Office/OfficeViewController.swift
  Workade/Views&ViewModels/Office/OfficeViewModel.swift
Labels: 화면구성/View Add, 기능 추가/Enhancement

#84 ✨ 워케이션뷰의 UI를 구성하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/Jejudo Map/Contents.json
  Workade/Assets.xcassets/Jejudo Map/Namwon.imageset/Contents.json
  Workade/Assets.xcassets/Jejudo Map/Namwon.imageset/Namwon.svg
  Workade/Assets.xcassets/Sticker/Contents.json
  Workade/Assets.xcassets/Sticker/TangerineSticker.imageset/Contents.json
  Workade/Assets.xcassets/Sticker/TangerineSticker.imageset/TangerineSticker.svg
  Workade/Extentions/UIColor+.swift
  Workade/Extentions/UIImage+.swift
  Workade/Share/GradientButton.swift
  Workade/Views&ViewModels/Workation/StickerSheet/StickerSheetViewController.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
  Workade/Views&ViewModels/Workation/WorkationViewModel.swift
  Workade/Views&ViewModels/Workation/WorkerStatusSheet/WorkerStatusSheetViewController.swift
Labels: 화면구성/View Add, 기능 추가/Enhancement

#85 ✨ 새로운 디자인의 MagazineViewController를 구성했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Managers/NetworkManager.swift
  Workade/Models/MagazineCategory.swift
  Workade/Models/MagazineResource.swift
  Workade/Share/PrepareView.swift
  Workade/Views&ViewModels/GuideHome/GuideHomeViewController.swift
  Workade/Views&ViewModels/Magazine/MagazineDetailView.swift
  Workade/Views&ViewModels/Magazine/MagazineViewController.swift
  Workade/Views&ViewModels/Magazine/MagazineViewModel/MagazineViewModel.swift
  Workade/Views&ViewModels/Magazine/TapDetailViewController.swift
  Workade/Views&ViewModels/Office/OfficeViewController.swift
  Workade/Views&ViewModels/Office/OfficeViewModel.swift
Labels: 화면구성/View Add, 기능 추가/Enhancement

#86 🍱 2차 스프린트를 위한 에셋 파일을 수정했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/AppIcon.appiconset/1024.png
  Workade/Assets.xcassets/AppIcon.appiconset/Contents.json
  Workade/Assets.xcassets/AppIcon.appiconset/logo.png
  Workade/Assets.xcassets/Colors/Quaternary.colorset/Contents.json
  Workade/Assets.xcassets/Colors/Secondary.colorset/Contents.json
  Workade/Assets.xcassets/Colors/SectionBackground.colorset/Contents.json
  Workade/Assets.xcassets/Colors/WorkadeBackgroundBlue.colorset/Contents.json
  Workade/Assets.xcassets/GalleryTestImage1.imageset/Contents.json
  Workade/Assets.xcassets/GalleryTestImage1.imageset/skystair.jpeg
  Workade/Assets.xcassets/GalleryTestImage2.imageset/601dd5c3fa4b5ed150659ef09fbf5f6f6ab78900cac8bebccacf06db87034547343bfcbdec1d432406cdb49211e290dbc57b77ace54f4c029a24445c47f3145fb55257185ede21de81a1a9623e50e8abe61e806b5b890f92250809e4f915574b22d5780ced2072f3996642f57a50dbe2.jpeg
  Workade/Assets.xcassets/GalleryTestImage2.imageset/Contents.json
  Workade/Assets.xcassets/GalleryTestImage3.imageset/Contents.json
  Workade/Assets.xcassets/GalleryTestImage3.imageset/sunghoon-kim-efAYaRFwm18-unsplash.jpg
  Workade/Assets.xcassets/GalleryTestImage4.imageset/Contents.json
  Workade/Assets.xcassets/GalleryTestImage4.imageset/ori-song-H819CP2ad-g-unsplash.jpg
  Workade/Assets.xcassets/VectorMap/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Aewol.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Aewol.imageset/Group 284.svg
  Workade/Assets.xcassets/VectorMap/Jeju/Andeok.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Andeok.imageset/Group 277.svg
  Workade/Assets.xcassets/VectorMap/Jeju/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Daejeong.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Daejeong.imageset/Group 278.svg
  Workade/Assets.xcassets/VectorMap/Jeju/Gujwa.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Gujwa.imageset/Group 289.svg
  Workade/Assets.xcassets/VectorMap/Jeju/Hankyung.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Hankyung.imageset/Group 282.svg
  Workade/Assets.xcassets/VectorMap/Jeju/Hanlim.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Hanlim.imageset/Group 283.svg
  Workade/Assets.xcassets/VectorMap/Jeju/Jeju.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Jeju.imageset/Group 285.svg
  Workade/Assets.xcassets/VectorMap/Jeju/Jocheon.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Jocheon.imageset/Group 286.svg
  Workade/Assets.xcassets/VectorMap/Jeju/Jungmun.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Jungmun.imageset/Group 281.svg
  Workade/Assets.xcassets/VectorMap/Jeju/Namwon.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Namwon.imageset/Group 263.svg
  Workade/Assets.xcassets/VectorMap/Jeju/Pyoseon.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Pyoseon.imageset/Group 288.svg
  Workade/Assets.xcassets/VectorMap/Jeju/Seogwipo.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Seogwipo.imageset/Group 280.svg
  Workade/Assets.xcassets/VectorMap/Jeju/Seongsan.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/Jeju/Seongsan.imageset/Group 287.svg
  Workade/Assets.xcassets/VectorMap/map.imageset/Contents.json
  Workade/Assets.xcassets/VectorMap/map.imageset/map.svg
  Workade/Assets.xcassets/blank.imageset/Contents.json
  Workade/Assets.xcassets/blank.imageset/blank.png
  Workade/Assets.xcassets/blank.imageset/blank_1.png
  Workade/Assets.xcassets/blank.imageset/blank_3x.png
  Workade/Assets.xcassets/folder.imageset/Contents.json
  Workade/Assets.xcassets/folder.imageset/FOLDER.png
  Workade/Assets.xcassets/officeImage_test.imageset/Contents.json
  Workade/Assets.xcassets/sampleTipImage.imageset/Contents.json
  Workade/Assets.xcassets/sampleTipImage.imageset/sampleTipImage.jpeg
  Workade/DesignSystem.swift
  Workade/Extentions/CAGradientLayer+.swift
  Workade/Extentions/UIColor+.swift
Labels: 문서/Document

#88 ✨프로필 수정 View 의 UI를 구성하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UITextField+.swift
  Workade/Views&ViewModels/MyPage/EditProfile/EditProfileViewController.swift
  Workade/Views&ViewModels/MyPage/EditProfile/PickerTableViewCell.swift
Labels: 기능 추가/Enhancement

#87 :sparkles: LoginView를 구현했습니다.
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Pods.xcodeproj/xcuserdata/inhochoi.xcuserdatad/xcschemes/Pods-Workade.xcscheme
  Pods/Pods.xcodeproj/xcuserdata/inhochoi.xcuserdatad/xcschemes/xcschememanagement.plist
  Workade.xcodeproj/project.pbxproj
  Workade.xcodeproj/xcuserdata/inhochoi.xcuserdatad/xcschemes/xcschememanagement.plist
  Workade/Assets.xcassets/Login/Contents.json
  Workade/Assets.xcassets/Login/loginimage.imageset/Contents.json
  Workade/Assets.xcassets/Login/loginimage.imageset/loginimage.pdf
  Workade/Views&ViewModels/Login/LoginView.swift
Labels: 화면구성/View Add, 기능 추가/Enhancement

#90 ✨ SettingViewController를 재구성 하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Share/SettingButton.swift
  Workade/Views&ViewModels/MyPage/EditProfile/EditProfileViewController.swift
  Workade/Views&ViewModels/MyPage/Setting/LoginInformationView.swift
  Workade/Views&ViewModels/MyPage/Setting/SettingViewController.swift
  Workade/Views&ViewModels/SettingViewController/SettingViewController.swift
Labels: 화면구성/View Add, 기능 추가/Enhancement

#91 ✨ 재사용 할 수 있는 Button을 생성하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/SceneDelegate.swift
  Workade/Share/LocationButton.swift
  Workade/Share/TestViewController.swift
Labels: 화면구성/View Add, 기능 추가/Enhancement

#92 ♻️ 2차 스프린트에 따라 체크리스트 로직과 디자인을 수정하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Managers/CoreDataManager.swift
  Workade/Views&ViewModels/CheckList/CheckListCell/CheckListAddButtonCell.swift
  Workade/Views&ViewModels/CheckList/CheckListCell/CheckListCell.swift
  Workade/Views&ViewModels/CheckList/CheckListCell/CheckListCellViewModel.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListBottomSheet/CheckListBottomSheetViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListBottomSheet/CheckListBottomSheetViewModel.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailCell/CheckListDetailCell.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListDetail/CheckListDetailViewModel.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListTemplate/CheckListTemplateViewModel.swift
  Workade/Views&ViewModels/CheckList/CheckListViewController.swift
  Workade/Views&ViewModels/CheckList/CheckListViewModel.swift
  Workade/Workade.xcdatamodeld/Workade.xcdatamodel/contents
Labels: 화면구성/View Add, 수정/Modify, 리팩토링/Refactoring

#96 ✨ 카카오 공유 기능, 기본 공유 기능을 구현했습니다.
  Pods/Pods.xcodeproj/project.pbxproj
  Workade.xcodeproj/project.pbxproj
  Workade.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Workade/AppDelegate.swift
  Workade/Assets.xcassets/ShareButtons/ClipboardButton.imageset/ClipboardButton.pdf
  Workade/Assets.xcassets/ShareButtons/ClipboardButton.imageset/Contents.json
  Workade/Assets.xcassets/ShareButtons/Contents.json
  Workade/Assets.xcassets/ShareButtons/DefaultButton.imageset/Contents.json
  Workade/Assets.xcassets/ShareButtons/DefaultButton.imageset/DefaultButton.pdf
  Workade/Assets.xcassets/ShareButtons/KakaoButton.imageset/Contents.json
  Workade/Assets.xcassets/ShareButtons/KakaoButton.imageset/KakaoButton.pdf
  Workade/Extentions/String+.swift
  Workade/Extentions/UIScrollView+.swift
  Workade/Info.plist
  Workade/SceneDelegate.swift
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
  Workade/Views&ViewModels/Magazine/ShareView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
Labels: 화면구성/View Add, 기능 추가/Enhancement

#93 ✨ 스티커를 획득하는 프로그레스뷰 UI를 추가하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Views&ViewModels/Workation/StickerProgress/StickerProgressView.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
Labels: 화면구성/View Add, 리뷰 완료/End Review, 리뷰 중/In Review

#101 ✨ 현재 위치정보를 불러오는 뷰모델 로직을 추가하였습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Views&ViewModels/Workation/WorkationViewModel.swift
Labels: 기능 추가/Enhancement

#99 ✨ OfficeCell과 MagazineCell을 눌러 present할 때 Transition 애니메이션을 적용했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UIViewPropertyAnimator+.swift
  Workade/Managers/CardTransitionManager.swift
  Workade/Managers/MagazineTransitionManager.swift
  Workade/Managers/OfficeTransitionManager.swift
  Workade/Share/CustomSegmentedControl.swift
  Workade/Share/PrepareView.swift
  Workade/Views&ViewModels/GuideHome/GuideHomeViewController.swift
  Workade/Views&ViewModels/GuideHome/View/CellImageView.swift
  Workade/Views&ViewModels/GuideHome/View/MagazineCollectionViewCell.swift
  Workade/Views&ViewModels/GuideHome/View/OfficeCollectionViewCell.swift
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
  Workade/Views&ViewModels/Magazine/MagazineViewController.swift
  Workade/Views&ViewModels/Magazine/TitleImageView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceImageView.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceViewController.swift
  Workade/Views&ViewModels/Office/OfficeViewController.swift
Labels: 화면구성/View Add, 기능 추가/Enhancement

#94 ✨ ExploreViewController를 추가했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Assets.xcassets/ExploreBackground/Contents.json
  Workade/Assets.xcassets/ExploreBackground/chungcheongbukdoBackground.imageset/Contents.json
  Workade/Assets.xcassets/ExploreBackground/chungcheongbukdoBackground.imageset/chungcheongbukdoBackground.png
  Workade/Assets.xcassets/ExploreBackground/chungcheongnamdoBackground.imageset/Contents.json
  Workade/Assets.xcassets/ExploreBackground/chungcheongnamdoBackground.imageset/chungcheongnamdoBackground.png
  Workade/Assets.xcassets/ExploreBackground/gangwondoBackground.imageset/Contents.json
  Workade/Assets.xcassets/ExploreBackground/gangwondoBackground.imageset/gangwondoBackground.png
  Workade/Assets.xcassets/ExploreBackground/gyeonggidoBackground.imageset/Contents.json
  Workade/Assets.xcassets/ExploreBackground/gyeonggidoBackground.imageset/gyeonggidoBackground.png
  Workade/Assets.xcassets/ExploreBackground/gyeongsangbukdoBackground.imageset/Contents.json
  Workade/Assets.xcassets/ExploreBackground/gyeongsangbukdoBackground.imageset/gyeongsangbukdoBackground.png
  Workade/Assets.xcassets/ExploreBackground/gyeongsangnamdoBackground.imageset/Contents.json
  Workade/Assets.xcassets/ExploreBackground/gyeongsangnamdoBackground.imageset/gyeongsangnamdoBackground.png
  Workade/Assets.xcassets/ExploreBackground/jejuBackground.imageset/Contents.json
  Workade/Assets.xcassets/ExploreBackground/jejuBackground.imageset/jejuBackground.png
  Workade/Assets.xcassets/ExploreBackground/jeollabukdoBackground.imageset/Contents.json
  Workade/Assets.xcassets/ExploreBackground/jeollabukdoBackground.imageset/jeollabukdoBackground.png
  Workade/Assets.xcassets/ExploreBackground/jeollanamdoBackground.imageset/Contents.json
  Workade/Assets.xcassets/ExploreBackground/jeollanamdoBackground.imageset/jeollanamdoBackground.png
  Workade/Assets.xcassets/Star.imageset/Contents.json
  Workade/Assets.xcassets/Star.imageset/Star.svg
  Workade/Assets.xcassets/icon.imageset/Contents.json
  Workade/Assets.xcassets/icon.imageset/w.svg
  Workade/Models/RegionModel.swift
  Workade/SceneDelegate.swift
  Workade/Share/GradientButton.swift
  Workade/Share/RegionButton.swift
  Workade/Views&ViewModels/Explore/ExploreViewController.swift
  Workade/Views&ViewModels/Explore/ExploreViewModel.swift
  Workade/Views&ViewModels/Explore/RegionInfoView.swift
Labels: 문서/Document, 기능 추가/Enhancement, 리뷰 중/In Review

#102 :bug: ViewModel 삭제로 인한 코드 반영 누락
  Workade/Views&ViewModels/Workation/StickerProgress/StickerProgressView.swift
Labels: 버그/Bug

#103 ✨ FirebaseMangager와 FirestoreDAO/DTO를 생성했습니다.
  .gitignore
  Workade.xcodeproj/project.pbxproj
  Workade.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Workade/AppDelegate.swift
  Workade/Extentions/Encodable+.swift
  Workade/Extentions/UIView+.swift
  Workade/Info.plist
  Workade/Managers/FirebaseManager.swift
  Workade/Managers/FirestoreManager.swift
  Workade/Models/JobModel.swift
  Workade/Models/UserModel.swift
  Workade/Views&ViewModels/Login/Element/JobPickerScrollView.swift
  Workade/Views&ViewModels/Login/Element/LoginButtonView.swift
  Workade/Views&ViewModels/Login/Element/LoginNextButtonView.swift
  Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
  Workade/Views&ViewModels/Login/LoginName/LoginNameViewController.swift
  Workade/Views&ViewModels/Login/LoginSheetView.swift
  Workade/Workade.entitlements
Labels: 기능 추가/Enhancement

#104 ♻️ 오피스 배너 이미지와 매거진 배너 이미지의 크기를 통일시켰습니다.
  Workade/Managers/MagazineTransitionManager.swift
  Workade/Managers/OfficeTransitionManager.swift
  Workade/Views&ViewModels/Magazine/CellItemDetailViewController.swift
  Workade/Views&ViewModels/NearbyPlace/NearbyPlaceImageView.swift
Labels: 리팩토링/Refactoring

#105 :sparkles: View 연결
  Workade.xcodeproj/project.pbxproj
  Workade/Info.plist
  Workade/Managers/FirebaseManager.swift
  Workade/Models/UserModel.swift
  Workade/Views&ViewModels/Explore/ExploreViewController.swift
  Workade/Views&ViewModels/Explore/RegionInfoView.swift
  Workade/Views&ViewModels/Login/Element/JobPickerScrollView.swift
  Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
  Workade/Views&ViewModels/Login/LoginName/LoginNameViewController.swift
  Workade/Views&ViewModels/Login/LoginSheetView.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
Labels: 화면구성/View Add

#106 ✨ ExploreViewController 트렌지션 추가 및 워케이션 가능 지역 경고 뷰를 추가했습니다.
  Workade.xcodeproj/project.pbxproj
  Workade/Managers/ExploreTransitionManager.swift
  Workade/Models/RegionModel.swift
  Workade/Views&ViewModels/Explore/ExploreViewController.swift
  Workade/Views&ViewModels/Explore/RegionInfoView.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
Labels: 기능 추가/Enhancement

#107 ♻️ Picker의 UI를 통일시키기 위해 수정 했습니다.
  Workade/Views&ViewModels/MyPage/EditProfile/EditProfileViewController.swift
  Workade/Views&ViewModels/MyPage/EditProfile/PickerTableViewCell.swift
Labels: 리팩토링/Refactoring

#108 :pencil2: 로그인 로직 및 로그인 뷰 연결
  Workade.xcodeproj/project.pbxproj
  Workade/Extentions/UIView+.swift
  Workade/Managers/FirebaseManager.swift
  Workade/Managers/UserManager.swift
  Workade/Models/UserModel.swift
  Workade/Views&ViewModels/Login/LoginInitViewController.swift
  Workade/Views&ViewModels/Login/LoginJob/LoginJobViewController.swift
  Workade/Views&ViewModels/Login/LoginSheetView.swift
  Workade/Views&ViewModels/Workation/WorkationViewController.swift
  Workade/Views&ViewModels/Workation/WorkationViewModel.swift
Labels: 기능 추가/Enhancement
